x-logging: &logging
  options:
    max-size: "256k"
    max-file: "1"
  driver: json-file

name: atomic-2
services:
  app:
    build:
      context: ./app
      network: host
    restart: always
    logging: *logging
    environment:
      - LLM_BASE_URL=$LLM_BASE_URL
      - LLM_API_KEY=$LLM_API_KEY
    ports:
      - "8080:7860"

  qdrant:
    image: qdrant/qdrant:v1.9.5
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_storage:/qdrant/storage:z

volumes:
  qdrant_storage: 
